### PR TITLE
We ran into a 'TypeError: Unicode-objects must be encoded before hashing" when using this in Python 3.6.  Adding 'utf-8' to the decode fixed it.

### PR DESCRIPTION
**Pull request by Patreon-Amber**
Copy-paste of the error:
internal error
Traceback (most recent call last):
  File "/root/venv/lib/python3.6/site-packages/_pytest/main.py", line 105, in wrap_session
    session.exitstatus = doit(config, session) or 0
  File "/root/venv/lib/python3.6/site-packages/_pytest/main.py", line 140, in _main
    config.hook.pytest_collection(session=session)
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/root/venv/lib/python3.6/site-packages/_pytest/main.py", line 150, in pytest_collection
    return session.perform_collect()
  File "/root/venv/lib/python3.6/site-packages/_pytest/main.py", line 607, in perform_collect
    config=self.config, items=items)
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 745, in __call__
    return self._hookexec(self, self._nonwrappers + self._wrappers, kwargs)
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 339, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 334, in <lambda>
    _MultiCall(methods, kwargs, hook.spec_opts).execute()
  File "/root/venv/lib/python3.6/site-packages/_pytest/vendored_packages/pluggy.py", line 614, in execute
    res = hook_impl.function(*args)
  File "/root/venv/lib/python3.6/site-packages/pytest_circleci/plugin.py", line 39, in pytest_collection_modifyitems
    item_hash = int(hashlib.sha1(':'.join(map(str, item.location))).hexdigest(), 16)
TypeError: Unicode-objects must be encoded before hashing

### CODE REVIEW

**Comment by philfreo** [comment]
@micktwomey Any reason not to merge and release this?

Also looking to understand if you're still maintaining this repo, and whether you're interested in getting Python 3 officially supported.

**Comment by Patreon-Amber** [comment]
> @micktwomey Any reason not to merge and release this?
> 
> Also looking to understand if you're still maintaining this repo, and whether you're interested in getting Python 3 officially supported.

I forked to https://github.com/Patreon/pytest-circleci and added this change there so we could use this instead of the the weird custom hackery that we had previously.  Its been working reliably on both Python 3.6 and 3.7 so I'm :+1: for merging and releasing, then I can drop my fork and use this upstream again.  This is the only problem we had with Python 3, everything else "just works"

**Comment by philfreo** [comment]
👍 Do you want to also update https://github.com/micktwomey/pytest-circleci/blob/c554ad41e0a250a75868911ffe04dbd817b32cb4/setup.py#L25 and https://github.com/micktwomey/pytest-circleci/blob/c554ad41e0a250a75868911ffe04dbd817b32cb4/tox.ini#L2 in your branch to reflect Python 3 support?

**Comment by Patreon-Amber** [comment]
> +1 Do you want to also update
> 
> [pytest-circleci/setup.py](https://github.com/micktwomey/pytest-circleci/blob/c554ad41e0a250a75868911ffe04dbd817b32cb4/setup.py#L25)
> 
> Line 25 in [c554ad4](/micktwomey/pytest-circleci/commit/c554ad41e0a250a75868911ffe04dbd817b32cb4)
>  # "Programming Language :: Python :: 3",  Not tested yet 
> and
> 
> [pytest-circleci/tox.ini](https://github.com/micktwomey/pytest-circleci/blob/c554ad41e0a250a75868911ffe04dbd817b32cb4/tox.ini#L2)
> 
> Line 2 in [c554ad4](/micktwomey/pytest-circleci/commit/c554ad41e0a250a75868911ffe04dbd817b32cb4)
>  envlist = py27,py34 
> in your branch to reflect Python 3 (and 3.7) support?

6c800e3 adds Py 3 to tox.ini and setup.py and bumps the version for a clean release.

**Comment by philfreo** [comment]
Awesome, thanks!

@micktwomey Any chance of getting this merged & released? Also, if you're looking for any help maintaining this project, just let us know.

**Comment by micktwomey** [comment]
Thank you very much for this! I apologise, I don't check very often for merge requests. I'll happily add folks to this project (or hand it over to someone else). I don't use CircleCI much at the moment so I don't get much opportunity to use this lib any more.

**Comment by Patreon-Amber** [comment]
> Thank you very much for this! I apologise, I don't check very often for merge requests. I'll happily add folks to this project (or hand it over to someone else). I don't use CircleCI much at the moment so I don't get much opportunity to use this lib any more.

No problem, just wanted to contribute back to upstream since this problem was pretty easy to fix.  Now we can drop our fork and move back to the original :+1:

**Comment by philfreo** [comment]
Thank you!

**Pull request merged**
